### ISSUE TITLE
Not an Issue - Just to get more informations

### ISSUE THREAD

**Issue by m01001101-01010110** [sunnyden/TizenYoutube#1]
Hello,

First of all, thank you for sharing your development codes.

I see this project "TizenYoutube". Does it work if I compile it with this code ?
Out of curiosity, I would like to know if this project will be developed further? With new features for example?

Thanks for your answers in advance.

Happy New Year!

**Comment by sunnyden** [comment]
This is a wrapper for starting YouTube TV for Samsung TV sold in China. It
just simply redirects the webpage to YouTube.com/tv, and YouTube will
handle the rest.
